#!/usr/bin/env bash
########
set -x
set -e

source /common.sh

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/boot /boot
unpack /filesystem/root_init /

# Update the package registry
apt-get update

# Setup x11vnc
apt-get install -y --force-yes x11vnc

sudo -u pi /home/pi/scripts/setX11vncPass raspberry
ls -l /home/pi/.vnc/passwd

# Enable x11vnc service
systemctl enable x11vnc.service

# Fix rotate.sh (by software)
apt-get install -y --force-yes xinput
sudo -u pi chmod +x /home/pi/scripts/rotate.sh

# Rotate by hardware
if [ "$SCREEN_ROTATION_HARDWARE" == "yes" ]
then
  # Disable gpu enablement service
  touch /etc/gpu_enabled

  sudo sed -i '/^dtoverlay=vc4-kms-v3d/ s/^/# /' /boot/config.txt
  printf "display_lcd_rotate=1\n" | sudo tee -a /boot/config.txt
  printf "dtoverlay=rpi-ft5406,touchscreen-swapped-x-y=1,touchscreen-inverted-x=1\n" | sudo tee -a /boot/config.txt

  echo "Rotation by hardware enabled"
fi

# Monitoring
apt-get install -y --force-yes glances

# Cleanup
apt-get clean
apt-get autoremove -y
